server:
  port: 8010
spring:
  application:
    name: account
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderingsystem?useUnicode=true&characterEncoding=UTF-8&useSSL=true
mybatis:
  mapper-locations: classpath:mappering/*.xml
  type-aliases-package: com.kevin.entity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
