server:
  port: 8030
spring:
  application:
    name: order
  datasource:
    name: orderingsystem
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/orderingsystem?useUnicode=true&characterEncoding=utf-8
mybatis:
  mapper-locations: classpath:mappering/*.xml
  type-aliases-package: com.kevin.entity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true